/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Match
         * @description Actualiza sólo los campos presentes en el body.
         *
         *     Enviar `"notes": null` borra las notas; omitir `notes` las deja intactas. El monolito no podía
         *     distinguir estos dos casos.
         */
        patch: operations["update_match_api_matches__game_id__patch"];
        trace?: never;
    };
    "/api/matches/{game_id}/scout-opponent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scout Opponent
         * @description Escout del rival de línea de una partida: sus 3 campeones más jugados (Champion Mastery).
         *
         *     La llamada a Riot se hace UNA vez por rival y se cachea en `scout_cache` (TTL 24h) para
         *     no quemar la cuota escouteando partidas repetidas del mismo jugador. `cached` distingue
         *     caché caliente de llamada fresca. Cuando no hay datos no se devuelve error: la respuesta
         *     trae una `note` explicando por qué (rival sin maestrías, rol sin asignar...).
         */
        get: operations["scout_opponent_api_matches__game_id__scout_opponent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/champions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Champions
         * @description Incluye `winrate` y `kda_ratio` calculados en SQL: las dos columnas que la Tab 3 de
         *     Streamlit pedía y que la query nunca devolvía.
         */
        get: operations["champions_api_stats_champions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/champion-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Champion Role Summary
         * @description Dónde rindes mejor: winrate/KDA por (campeón, rol, cola) con mínimo de 3 partidas.
         *
         *     Es el desglose que los stats globales no ven: una caída en el winrate general puede
         *     venir solo de jugar en una cola de normales o de un rol fuera del pool. `HAVING` en SQL
         *     descarta las combinaciones con menos de 3 partidas, donde el winrate es ruido.
         */
        get: operations["champion_role_summary_api_stats_champion_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/session-fatigue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Fatigue
         * @description Estado de sesión: compara las últimas 5 partidas con las 5 anteriores.
         *
         *     Detecta autopilot (caída severa de winrate/KDA entre bloques) para el banner "Estado de
         *     Sesión" del Dashboard. `sample_ok` es False cuando no hay 10 partidas válidas aún; el
         *     frontend muestra el `message` informativo igualmente.
         */
        get: operations["session_fatigue_api_stats_session_fatigue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_stats_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/patch-alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Patch Alert Endpoint
         * @description Alerta de parche: caída de winrate del Champion Pool tras una actualización.
         *
         *     Resuelve el parche actual desde Data Dragon (caché 1h), lo normaliza a "X.Y" y compara
         *     el winrate de los 3 campeones más jugados en ese parche contra su historial previo.
         *     `has_current_games` distingue el caso de "parche recién salido sin partidas aún".
         */
        get: operations["patch_alert_endpoint_api_stats_patch_alert_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/lp-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lp Trend
         * @description LP acumulado en orden cronológico. `has_lp` distingue "0 LP" de "aún sin registrar".
         *
         *     `queue` acota la cola (420 = Solo/Duo): las normales sin LP diluyen la curva si cuentan como 0.
         */
        get: operations["lp_trend_api_stats_lp_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kpi Trends
         * @description Serie temporal de KPIs de mejora (CS/min, DPM, KDA) de las últimas partidas válidas.
         *
         *     Ignora remakes (< 5 min); los DPM de filas legacy sin participants llegan como 0.
         */
        get: operations["kpi_trends_api_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/laning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Laning
         * @description Triángulo del Laning: promedios GD@15 / XPD@15 / CSD@15 (Timeline de Riot).
         *
         *     `games_analyzed` dice cuántas de las últimas 50 partidas válidas tenían datos de
         *     timeline (0 recién instalado, antes del primer sync con la nueva extracción); los
         *     promedios son None sin ninguna partida.
         */
        get: operations["laning_api_stats_laning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weekly Report
         * @description Resumen de la última semana (7 días, fecha UTC): partidas, winrate, KDA, top campeón
         *     y mejor partida por rating. `most_played`/`best_match` son null si no hay partidas en la ventana.
         */
        get: operations["weekly_report_api_stats_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/meta-verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta Verdict
         * @description Veredicto del meta: winrate por emparejamiento (tú vs enemigo) en el parche actual
         *     contra el histórico de todos los parches anteriores.
         *
         *     Es la extensión de la Alerta de Parche a la matriz de matchups: cruza `champion` vs
         *     `enemy_champion` y separa las partidas de la `game_version` actual del historial previo.
         *     `meta_shift` marca los emparejamientos que eran favorables (winrate previo >= 55% con
         *     muestra previa) y ahora caen por debajo del 50% — la alerta de "el meta se te ha dado la
         *     vuelta" que el frontend resalta en la vista Matchups.
         */
        get: operations["meta_verdict_api_stats_meta_verdict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/matchups/{user_champion}/{enemy_champion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matchup Stats
         * @description Estadísticas históricas del cruce de dos campeones.
         *
         *     Filtra por campeón del usuario contra el rival de línea. Con cero partidas devuelve
         *     todo a 0 (no 404), porque la vista Matchups sigue funcionando con notas aunque no
         *     haya historial del cruce.
         */
        get: operations["matchup_stats_api_stats_matchups__user_champion___enemy_champion__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matchup-notes/{user_champion}/{enemy_champion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Notes
         * @description Notas del cruce. Si nunca se guardó nada, devuelve notas vacías (no 404).
         */
        get: operations["get_notes_api_matchup_notes__user_champion___enemy_champion__get"];
        /**
         * Put Notes
         * @description Guarda/reemplaza las notas del cruce (PUT semantics).
         */
        put: operations["put_notes_api_matchup_notes__user_champion___enemy_champion__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/riot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Link Riot
         * @description Vincula (o re-vincula) el Riot ID del usuario.
         *
         *     Mismo patrón de respuesta que PUT /api/config: devuelve la fila resultante ya
         *     normalizada (el validators del schema limpia `riot_id` y pasa `region` a mayúsculas).
         */
        put: operations["link_riot_api_settings_riot_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Encola la sincronización del usuario logueado y responde al instante (202).
         *
         *     La validación (Riot ID vinculado, colas) sigue siendo síncrona: los errores de petición se
         *     reportan aquí, no en el polling. Los fallos de Riot/DB viajan después por `/status`. El Riot
         *     ID y la región se leen de `user_settings` (migración 014), no del .env.
         */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description Estado del sync del usuario para el polling del frontend (idle/processing/success/partial/error).
         *
         *     Cada usuario consulta SU propio estado (el dict `_states` está aislado por user_id).
         */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Config completa: canónicos del sistema + configuración persistida del usuario.
         *
         *     En Streamlit, `IMPACT_RATINGS` estaba hardcodeado en dos formularios distintos con riesgo
         *     de divergencia. Ahora vive en un solo sitio y se sirve desde la API.
         */
        get: operations["get_config_api_config_get"];
        /**
         * Update Config
         * @description Reemplaza champion pool y OKRs (PUT semantics).
         *
         *     El pool se limpia en el servidor: quita blancos y duplicados, respeta el máximo de 3
         *     (regla de La Constitución).
         */
        put: operations["update_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/champions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Champions
         * @description Campeones del parche vigente. Clave = id de Data Dragon ('LeeSin'); `name` es el nombre
         *     visible que la DB guarda en matches.champion/participants.champion_name.
         */
        get: operations["champions_api_metadata_champions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Items
         * @description Objetos del parche vigente. Clave = id numérico de Riot ('3078').
         */
        get: operations["items_api_metadata_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spells
         * @description Hechizos de invocador. Clave = id numérico de partida ('4' = Flash).
         */
        get: operations["spells_api_metadata_spells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChampionMeta */
        ChampionMeta: {
            /**
             * Id
             * @description Id de Data Dragon ('LeeSin'), clave del dict
             */
            id: string;
            /**
             * Key
             * @description Id numérico de Data Dragon ('103'), el de Champion Mastery-V4
             * @default
             */
            key: string;
            /**
             * Name
             * @description Nombre visible ('Lee Sin') — así se guarda en matches.champion
             */
            name: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image
             * @description URL absoluta del cuadrado en Data Dragon
             */
            image: string;
        };
        /**
         * ChampionRoleSummary
         * @description Winrate/KDA del usuario por (campeón, rol, cola).
         *
         *     Con `HAVING COUNT(*) >= 3` en SQL: con menos partidas el winrate es puro ruido y la
         *     tabla no puede separar "rindo bien" de "he tenido suerte dos veces". El rol es la
         *     columna `matches.role` (el teamPosition que Riot reportó en la partida), no el
         *     `team_position` del JSONB: aquí importa cómo llegó la fila, una fila = una partida.
         */
        ChampionRoleSummary: {
            /** Champion */
            champion: string;
            /** Role */
            role: string;
            /** Queue Id */
            queue_id: number;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Kda Ratio */
            kda_ratio: number;
        };
        /**
         * ChampionStats
         * @description Incluye `winrate` y `kda_ratio`, que la query original nunca devolvía pese a que la
         *     Tab 3 las pedía -> KeyError permanente. Ahora se calculan en SQL.
         */
        ChampionStats: {
            /** Champion */
            champion: string;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Kda Ratio */
            kda_ratio: number;
            /** Avg Cs Min */
            avg_cs_min: number;
            /**
             * Avg Dpm
             * @default 0
             */
            avg_dpm: number;
        };
        /** ChampionsIndex */
        ChampionsIndex: {
            /** Patch */
            patch: string;
            /** Champions */
            champions: {
                [key: string]: components["schemas"]["ChampionMeta"];
            };
        };
        /** EndpointMetric */
        EndpointMetric: {
            /** Method */
            method: string;
            /**
             * Path
             * @description Plantilla de ruta ('/api/matches/{game_id}'), no el path literal
             */
            path: string;
            /** Count */
            count: number;
            /**
             * Errors
             * @description Peticiones terminadas en 5xx o excepción
             */
            errors: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** Max Ms */
            max_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /** Riot Key Present */
            riot_key_present: boolean;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** HeatmapCell */
        HeatmapCell: {
            /**
             * Day Of Week
             * @description 0 = Domingo, 1 = Lunes ... 6 = Sábado
             */
            day_of_week: number;
            /**
             * Time Block
             * @description Madrugada | Mañana | Tarde | Noche
             */
            time_block: string;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
        };
        /**
         * HeatmapResponse
         * @description Wrapper del heatmap: celdas + mejor/peor horario (con umbral mínimo de 3 partidas).
         */
        HeatmapResponse: {
            /** Cells */
            cells: components["schemas"]["HeatmapCell"][];
            best_slot?: components["schemas"]["HeatmapCell"] | null;
            worst_slot?: components["schemas"]["HeatmapCell"] | null;
        };
        /** ItemMeta */
        ItemMeta: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @description Descripción sin etiquetas HTML
             * @default
             */
            description: string;
            /** Image */
            image: string;
        };
        /** ItemsIndex */
        ItemsIndex: {
            /** Patch */
            patch: string;
            /** Items */
            items: {
                [key: string]: components["schemas"]["ItemMeta"];
            };
        };
        /**
         * LaningSummary
         * @description Promedios del Triángulo del Laning sobre las últimas partidas con datos de Timeline.
         *
         *     `games_analyzed` = cuántas partidas (de la ventana) alimentaron el promedio; 0 cuando los
         *     datos de timeline aún no se han sincronizado. Los promedios son None sin ninguna partida.
         */
        LaningSummary: {
            /**
             * Avg Gd15
             * @description Diferencia media de oro a los 15:00 (a tu favor si >0)
             */
            avg_gd15?: number | null;
            /**
             * Avg Xpd15
             * @description Diferencia media de XP a los 15:00
             */
            avg_xpd15?: number | null;
            /**
             * Avg Csd15
             * @description Diferencia media de CS a los 15:00
             */
            avg_csd15?: number | null;
            /**
             * Games Analyzed
             * @description Partidas con datos de timeline en la ventana (mínimo piramidal del triángulo)
             * @default 0
             */
            games_analyzed: number;
        };
        /**
         * LpCapture
         * @description LP de Solo/Duo capturado automáticamente al cerrar el sync (League-V4).
         *
         *     `delta_assigned` es el LP neto escrito como `lp_change` en la partida más reciente sin
         *     review manual; None cuando no había snapshot previo (línea base), delta 0, o ninguna
         *     partida candidata. Nunca sobrescribe una review del usuario.
         */
        LpCapture: {
            /** Lp */
            lp: number;
            /** Tier */
            tier?: string | null;
            /** Division */
            division?: string | null;
            /** Delta Assigned */
            delta_assigned?: number | null;
        };
        /**
         * Match
         * @description Una partida. Los campos objetivos vienen de Riot; los subjetivos los rellena el usuario.
         */
        Match: {
            /** Game Id */
            game_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Champion */
            champion: string;
            /** Role */
            role: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Cs Total */
            cs_total: number;
            /** Cs Min */
            cs_min: number;
            /** Control Wards */
            control_wards: number;
            /** Win */
            win: boolean;
            /** Enemy Champion */
            enemy_champion?: string | null;
            /** Game Duration Minutes */
            game_duration_minutes?: number | null;
            /** Queue Id */
            queue_id?: number | null;
            /** Participants */
            participants?: components["schemas"]["Participant"][] | null;
            /** Lp Change */
            lp_change?: number | null;
            /** Tilt Level */
            tilt_level?: number | null;
            /** Impact Rating */
            impact_rating?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Vod Review
             * @default false
             */
            vod_review: boolean;
        };
        /**
         * MatchUpdate
         * @description Actualización parcial de los campos subjetivos.
         *
         *     Ojo: en el monolito, `update_match_details` se saltaba los `None`, así que era imposible
         *     devolver un campo a NULL. Aquí se distingue "no enviado" (ausente del JSON) de "enviado como
         *     null" usando `model_fields_set`, así que sí se puede borrar un valor mal introducido.
         */
        MatchUpdate: {
            /** Lp Change */
            lp_change?: number | null;
            /** Tilt Level */
            tilt_level?: number | null;
            /** Impact Rating */
            impact_rating?: string | null;
            /** Notes */
            notes?: string | null;
            /** Vod Review */
            vod_review?: boolean | null;
        };
        /**
         * MatchupNotes
         * @description Notas persistidas para un emparejamiento concreto.
         */
        MatchupNotes: {
            /** User Champion */
            user_champion: string;
            /** Enemy Champion */
            enemy_champion: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * MatchupNotesUpdate
         * @description Payload del PUT: reemplazo completo de las notas del cruce.
         */
        MatchupNotesUpdate: {
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * MatchupStats
         * @description Estadísticas históricas del cruce de dos campeones (Tú contra enemigo).
         */
        MatchupStats: {
            /** User Champion */
            user_champion: string;
            /** Enemy Champion */
            enemy_champion: string;
            /**
             * Games Played
             * @default 0
             */
            games_played: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Winrate
             * @default 0
             */
            winrate: number;
            /**
             * Avg Kills
             * @default 0
             */
            avg_kills: number;
            /**
             * Avg Deaths
             * @default 0
             */
            avg_deaths: number;
            /**
             * Avg Assists
             * @default 0
             */
            avg_assists: number;
            /**
             * Kda Ratio
             * @default 0
             */
            kda_ratio: number;
        };
        /**
         * MetaVerdict
         * @description Winrate de un enfrentamiento (tu campeón vs enemigo) separado por parche.
         *
         *     `games_*_current` = partidas de la `game_version` del parche actual; `games_previous` =
         *     todo el historial de parches anteriores (incluidas las filas legacy con versión NULL).
         *     `meta_shift` marca exactamente el caso que alarma al usuario: un cruce que era favorable
         *     y ahora está por debajo del 50% — la alerta de "el meta te ha pasado por encima".
         */
        MetaVerdict: {
            /** User Champion */
            user_champion: string;
            /** Enemy Champion */
            enemy_champion: string;
            /** Games Current */
            games_current: number;
            /** Wins Current */
            wins_current: number;
            /**
             * Winrate Current
             * @description NULL sin partidas en el parche actual
             */
            winrate_current?: number | null;
            /** Games Previous */
            games_previous: number;
            /** Wins Previous */
            wins_previous: number;
            /**
             * Winrate Previous
             * @description NULL sin historial previo
             */
            winrate_previous?: number | null;
            /**
             * Delta Pp
             * @description winrate (parche actual) - winrate (anterior), en puntos
             */
            delta_pp?: number | null;
            /**
             * Meta Shift
             * @description Favorable antes, negativo ahora, con muestra mínima
             * @default false
             */
            meta_shift: boolean;
        };
        /** MetaVerdictResponse */
        MetaVerdictResponse: {
            /**
             * Current Patch
             * @description Parche de Riot normalizado a 'X.Y' con el que se separaron los datos
             */
            current_patch: string;
            /** Verdicts */
            verdicts: components["schemas"]["MetaVerdict"][];
        };
        /** MetricsSnapshot */
        MetricsSnapshot: {
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Endpoints */
            endpoints: components["schemas"]["EndpointMetric"][];
        };
        /**
         * Participant
         * @description Un jugador dentro de una partida (10 por match).
         *
         *     `player_name` sustituye al viejo `summoner_name` (que Riot ya no rellena en Match-V5): ahora
         *     se guarda el Riot ID completo "GameName#TAG". Los campos con default toleran filas antiguas
         *     del JSONB sincronizadas antes del nuevo esquema, para que /api/matches no reviente; tras un
         *     TRUNCATE + resync todos los participantes salen completos.
         */
        Participant: {
            /** Champion Name */
            champion_name: string;
            /**
             * Puuid
             * @default
             */
            puuid: string;
            /**
             * Player Name
             * @description Riot ID completo 'GameName#TAG'
             * @default
             */
            player_name: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Cs */
            cs: number;
            /**
             * Items
             * @description 7 IDs de items: item0-item5 + trinket en item6 (0 = slot vacío)
             */
            items?: number[];
            /**
             * Summoner Spells
             * @description 2 IDs de hechizos
             */
            summoner_spells?: number[];
            /** Team Id */
            team_id: number;
            /** Team Position */
            team_position: string;
            /** Win */
            win: boolean;
            /**
             * Total Damage
             * @description totalDamageDealtToChampions de Riot
             * @default 0
             */
            total_damage: number;
            /**
             * Total Damage Taken
             * @default 0
             */
            total_damage_taken: number;
            /**
             * Gold Earned
             * @default 0
             */
            gold_earned: number;
            /**
             * Vision Score
             * @default 0
             */
            vision_score: number;
            /**
             * Kill Participation
             * @default 0
             */
            kill_participation: number;
            /**
             * Rating
             * @description Rating universal 0-100
             * @default 0
             */
            rating: number;
            /**
             * Rating Version
             * @description Versión de la fórmula que generó `rating` (trazabilidad)
             * @default 1
             */
            rating_version: number;
            /**
             * Gd15
             * @description Diferencia de oro a los 15:00 (a tu favor si >0)
             */
            gd15?: number | null;
            /**
             * Xpd15
             * @description Diferencia de XP a los 15:00
             */
            xpd15?: number | null;
            /**
             * Csd15
             * @description Diferencia de CS (minions+jungle) a los 15:00
             */
            csd15?: number | null;
            /** @description Valores esperados de este rol para la duración de la partida */
            expected_stats?: components["schemas"]["ParticipantExpectedStats"] | null;
        };
        /**
         * ParticipantExpectedStats
         * @description Valores esperados de un rol para una partida concreta (baselines, no persistidos).
         */
        ParticipantExpectedStats: {
            /** Cs Per Min */
            cs_per_min: number;
            /** Dpm */
            dpm: number;
            /**
             * Kill Participation
             * @description Ratio 0-1
             */
            kill_participation: number;
            /**
             * Vision Score
             * @description Visión total esperada = visión/min × duración real
             */
            vision_score: number;
        };
        /**
         * PatchAlert
         * @description Alerta de parche: siempre devuelve datos; el frontend decide si mostrar banner según
         *     `has_current_games` (parche demasiado nuevo = sin partidas aún) y `alerting_champions`.
         */
        PatchAlert: {
            /** Current Patch */
            current_patch: string;
            /** Has Current Games */
            has_current_games: boolean;
            /** Alerting Champions */
            alerting_champions?: string[];
            /** Champions */
            champions: components["schemas"]["PatchChampionInfo"][];
        };
        /**
         * PatchChampionInfo
         * @description Rendimiento de un campeón del pool en el parche actual vs. los anteriores.
         */
        PatchChampionInfo: {
            /** Champion */
            champion: string;
            /** Games Current */
            games_current: number;
            /** Wins Current */
            wins_current: number;
            /**
             * Winrate Current
             * @description NULL si no hay partidas en el parche actual
             */
            winrate_current?: number | null;
            /** Games Previous */
            games_previous: number;
            /** Wins Previous */
            wins_previous: number;
            /**
             * Winrate Previous
             * @description NULL si el campeón nunca se jugó antes
             */
            winrate_previous?: number | null;
            /**
             * Delta Pp
             * @description winrate actual - winrate previo, en puntos porcentuales
             */
            delta_pp?: number | null;
            /**
             * Dropped
             * @description Caída >4pp con mínimo de 5 partidas en el parche actual
             * @default false
             */
            dropped: boolean;
        };
        /**
         * RiotLinkRequest
         * @description Cuerpo de PUT /api/settings/riot: vincula la cuenta Riot del usuario.
         *
         *     El Riot ID es el `GameName#TAG` que Riot usa para resolver el PUUID en el sync. La
         *     validación (formato + región conocida) vive en el servidor: el onboarding de la v2.1
         *     sólo envía `{riot_id, region}` y no valida nada por su cuenta.
         */
        RiotLinkRequest: {
            /**
             * Riot Id
             * @description Riot ID, formato 'Nombre#TAG'
             */
            riot_id: string;
            /**
             * Region
             * @description Región de plataforma (ROUTING_MAP)
             * @default EUW1
             */
            region: string;
        };
        /** ScoutMasteryChampion */
        ScoutMasteryChampion: {
            /**
             * Champion
             * @description Nombre visible del campeón ('Lee Sin')
             */
            champion: string;
            /**
             * Champion Key
             * @description Id numérico de Data Dragon ('103')
             */
            champion_key: string;
            /**
             * Mastery Level
             * @description Nivel de maestría (sin tope: Riot eliminó el cap de 7 en 2026)
             */
            mastery_level: number;
            /**
             * Points
             * @description Puntos de maestría acumulados
             */
            points: number;
        };
        /**
         * ScoutOpponent
         * @description Escout de un rival de línea concreto: sus 3 campeones más jugados vía Champion Mastery.
         *
         *     `opponent_champion` es lo que jugó contra ti en la partida escouteada; `top_champions`
         *     son sus maestrías más altas (ordenadas por puntos). `cached` dice si la respuesta vino de
         *     la caché en DB (`scout_cache`, TTL 24h) o de una llamada fresca a Riot — el front lo usa
         *     para no alarmarse si la llamada tarda.
         *
         *     `note` explica por qué no hay datos cuando los hay (rival sin maestrías, puuid ausente,
         *     rol sin asignar...), para que la UI muestre un mensaje útil en vez de un hueco.
         */
        ScoutOpponent: {
            /** Game Id */
            game_id: string;
            /** Opponent Puuid */
            opponent_puuid: string;
            /**
             * Opponent Name
             * @default
             */
            opponent_name: string;
            /**
             * Opponent Champion
             * @default
             */
            opponent_champion: string;
            /**
             * Opponent Role
             * @default
             */
            opponent_role: string;
            /** Top Champions */
            top_champions?: components["schemas"]["ScoutMasteryChampion"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Cached At */
            cached_at?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * SessionBlock
         * @description Un bloque de partidas consecutivas (las 5 más recientes o las 5 anteriores).
         */
        SessionBlock: {
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Avg Kda */
            avg_kda: number;
        };
        /**
         * SessionFatigue
         * @description Diagnóstico de fatiga de sesión comparando dos bloques de 5 partidas.
         *
         *     Las 10 partidas válidas más recientes se parten en dos bloques: `recent` (las 5 más
         *     nuevas) vs `previous` (las 5 que las preceden). `sample_ok` exige ambas ventanas
         *     completas — con menos de 6 partidas no hay bloque anterior y nada que comparar.
         *
         *     `fatigue_detected` (autopilot) se activa con una caída severa de winrate (>=20pp) o un
         *     desplome de KDA (>=2.0) entre bloques; los umbrales viven en `repositories/stats.py`
         *     porque son reglas de negocio, no de contrato. `message` da contexto en español con
         *     números reales, no un veredicto seco.
         */
        SessionFatigue: {
            previous?: components["schemas"]["SessionBlock"] | null;
            recent?: components["schemas"]["SessionBlock"] | null;
            /**
             * Sample Ok
             * @default false
             */
            sample_ok: boolean;
            /** Winrate Delta Pp */
            winrate_delta_pp?: number | null;
            /** Kda Delta */
            kda_delta?: number | null;
            /**
             * Fatigue Detected
             * @default false
             */
            fatigue_detected: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** SpellMeta */
        SpellMeta: {
            /**
             * Id
             * @description Id numérico del hechizo en el API de partida (4 = Flash)
             */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Image */
            image: string;
        };
        /** SpellsIndex */
        SpellsIndex: {
            /** Patch */
            patch: string;
            /** Spells */
            spells: {
                [key: string]: components["schemas"]["SpellMeta"];
            };
        };
        /**
         * SyncAccepted
         * @description Respuesta inmediata del POST /api/sync: el trabajo pesado corre en BackgroundTasks.
         */
        SyncAccepted: {
            /**
             * Status
             * @constant
             */
            status: "processing";
            /** Message */
            message: string;
        };
        /** SyncError */
        SyncError: {
            /** Game Id */
            game_id: string;
            /** Reason */
            reason: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * SyncResult
         * @description El sync ya no miente. El monolito decía "✨ Todo actualizado" incluso cuando un 429 había
         *     descartado partidas en silencio; ahora los fallos viajan en la respuesta.
         */
        SyncResult: {
            /** Fetched */
            fetched: number;
            /** Inserted */
            inserted: number;
            /** Skipped */
            skipped: number;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["SyncError"][];
            lp_captured?: components["schemas"]["LpCapture"] | null;
            /**
             * Losing Streak Warning
             * @description True si las últimas 3+ partidas son derrotas consecutivas (Tilt Alert)
             * @default false
             */
            losing_streak_warning: boolean;
            /**
             * Degraded Api
             * @description True si Riot se degradó a mitad del sync: se guardó el progreso parcial pero no se pudo completar. Reintenta con otro POST (insert_many es idempotente).
             * @default false
             */
            degraded_api: boolean;
        };
        /**
         * SyncStatus
         * @description Estado del sync en curso (o del último terminado), para el polling del frontend.
         *
         *     `partial` = terminó con Riot degradado: `result.degraded_api` es True y lo descargado
         *     hasta entonces quedó guardado.
         */
        SyncStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "processing" | "success" | "partial" | "error";
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            result?: components["schemas"]["SyncResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * TrendPoint
         * @description Un punto de la serie temporal de KPIs de mejora (últimas N partidas válidas).
         *
         *     Orden cronológico ascendente (partida más antigua primero) para que las gráficas de
         *     línea recorran el tiempo de izquierda a derecha. `timestamp` es la hora de juego en UTC.
         *
         *     `vision_delta` y `kp` se leen del JSONB `participants` (nulos en filas legacy o cuando
         *     no existe rival directo); `win` es el resultado de la partida, siempre presente.
         */
        TrendPoint: {
            /** Game Id */
            game_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Cs Min */
            cs_min: number;
            /** Dpm */
            dpm: number;
            /** Kda */
            kda: number;
            /** Vision Delta */
            vision_delta?: number | null;
            /** Kp */
            kp?: number | null;
            /** Win */
            win: boolean;
        };
        /**
         * UserSettings
         * @description Config completa del frontend: valores canónicos + configuración persistida del usuario.
         *
         *     GET /api/config devuelve todo junto para que el frontend no necesite múltiples llamadas.
         *     Los campos canónicos (impact_ratings, regions, etc.) son de solo lectura; los campos
         *     editables (champion_pool, target_cs_min, max_deaths) se actualizan con PUT.
         */
        UserSettings: {
            /** Champion Pool */
            champion_pool: string[];
            /** Target Cs Min */
            target_cs_min: number;
            /** Max Deaths */
            max_deaths: number;
            /**
             * Target Dpm
             * @description Meta de DPM (Daño Por Minuto)
             * @default 500
             */
            target_dpm: number;
            /**
             * Target Kp Percent
             * @description Meta de Kill Participation en %
             * @default 50
             */
            target_kp_percent: number;
            /**
             * Target Vision Score
             * @description Meta de Vision Score por partida
             * @default 20
             */
            target_vision_score: number;
            /** Updated At */
            updated_at?: string | null;
            /** Impact Ratings */
            impact_ratings?: string[];
            /** Regions */
            regions?: string[];
            /**
             * Champion Pool Max
             * @default 3
             */
            champion_pool_max: number;
            /**
             * Display Timezone
             * @default Europe/Madrid
             */
            display_timezone: string;
            /**
             * Riot Id
             * @default
             */
            riot_id: string;
            /**
             * Riot Region
             * @default EUW1
             */
            riot_region: string;
        };
        /**
         * UserSettingsUpdate
         * @description Reemplazo completo de la configuración (semántica de PUT).
         */
        UserSettingsUpdate: {
            /**
             * Champion Pool
             * @description Máximo 3 campeones (regla de La Constitución)
             */
            champion_pool: string[];
            /**
             * Target Cs Min
             * @description Meta de CS por minuto
             */
            target_cs_min: number;
            /**
             * Max Deaths
             * @description Tope de muertes por partida
             */
            max_deaths: number;
            /**
             * Target Dpm
             * @description Meta de DPM
             * @default 500
             */
            target_dpm: number;
            /**
             * Target Kp Percent
             * @description Meta de Kill Participation en %
             * @default 50
             */
            target_kp_percent: number;
            /**
             * Target Vision Score
             * @description Meta de Vision Score
             * @default 20
             */
            target_vision_score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeeklyBestMatch
         * @description La mejor partida de la semana, según el rating 0-100 del usuario.
         */
        WeeklyBestMatch: {
            /** Game Id */
            game_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Champion */
            champion: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Kda */
            kda: number;
            /** Rating */
            rating: number;
        };
        /**
         * WeeklyReport
         * @description Resumen de los últimos 7 días (ventana según fecha UTC) para el Reporte Semanal.
         */
        WeeklyReport: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Total Games */
            total_games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /**
             * Winrate
             * @default 0
             */
            winrate: number;
            /**
             * Avg Kda
             * @default 0
             */
            avg_kda: number;
            most_played?: components["schemas"]["WeeklyTopChampion"] | null;
            best_match?: components["schemas"]["WeeklyBestMatch"] | null;
        };
        /**
         * WeeklyTopChampion
         * @description Campeón más jugado de la semana (nombre visible; el avatar lo resuelve el frontend vía Data Dragon).
         */
        WeeklyTopChampion: {
            /** Champion */
            champion: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    list_matches_api_matches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filtro: 'ranked' o 'normal' */
                queue?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_api_matches__game_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scout_opponent_api_matches__game_id__scout_opponent_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoutOpponent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    champions_api_stats_champions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionStats"][];
                };
            };
        };
    };
    champion_role_summary_api_stats_champion_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionRoleSummary"][];
                };
            };
        };
    };
    session_fatigue_api_stats_session_fatigue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFatigue"];
                };
            };
        };
    };
    heatmap_api_stats_heatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapResponse"];
                };
            };
        };
    };
    patch_alert_endpoint_api_stats_patch_alert_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchAlert"];
                };
            };
        };
    };
    lp_trend_api_stats_lp_trend_get: {
        parameters: {
            query?: {
                limit?: number;
                queue?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kpi_trends_api_stats_trends_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    laning_api_stats_laning_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaningSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_report_api_stats_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
        };
    };
    meta_verdict_api_stats_meta_verdict_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaVerdictResponse"];
                };
            };
        };
    };
    matchup_stats_api_stats_matchups__user_champion___enemy_champion__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_champion: string;
                enemy_champion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notes_api_matchup_notes__user_champion___enemy_champion__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_champion: string;
                enemy_champion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupNotes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_notes_api_matchup_notes__user_champion___enemy_champion__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_champion: string;
                enemy_champion: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchupNotesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupNotes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_riot_api_settings_riot_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiotLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: {
                limit?: number;
                /** @description IDs de cola separados por coma (420=Solo/Duo, 400=Normal Draft). Default: ambos. */
                queues?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
        };
    };
    update_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    champions_api_metadata_champions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionsIndex"];
                };
            };
        };
    };
    items_api_metadata_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsIndex"];
                };
            };
        };
    };
    spells_api_metadata_spells_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpellsIndex"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSnapshot"];
                };
            };
        };
    };
}
