/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_api_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Match */
        get: operations["get_match_api_matches__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Match
         * @description Actualiza sólo los campos presentes en el body.
         *
         *     Enviar `"notes": null` borra las notas; omitir `notes` las deja intactas. El monolito no podía
         *     distinguir estos dos casos.
         */
        patch: operations["update_match_api_matches__game_id__patch"];
        trace?: never;
    };
    "/api/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Promedios como números. El monolito devolvía la KDA como el string "5.0 / 2.0 / 10.0",
         *     que la UI re-parseaba con `.split('/')` — origen del bug de `app.py:128`.
         */
        get: operations["summary_api_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/champions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Champions
         * @description Incluye `winrate` y `kda_ratio` calculados en SQL: las dos columnas que la Tab 3 de
         *     Streamlit pedía y que la query nunca devolvía.
         */
        get: operations["champions_api_stats_champions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_stats_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/lp-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lp Trend
         * @description LP acumulado en orden cronológico. `has_lp` distingue "0 LP" de "aún sin registrar".
         *
         *     `queue` acota la cola (420 = Solo/Duo): las normales sin LP diluyen la curva si cuentan como 0.
         */
        get: operations["lp_trend_api_stats_lp_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kpi Trends
         * @description Serie temporal de KPIs de mejora (CS/min, DPM, KDA) de las últimas partidas válidas.
         *
         *     Ignora remakes (< 5 min); los DPM de filas legacy sin participants llegan como 0.
         */
        get: operations["kpi_trends_api_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weekly Report
         * @description Resumen de la última semana (7 días, fecha UTC): partidas, winrate, KDA, top campeón
         *     y mejor partida por rating. `most_played`/`best_match` son null si no hay partidas en la ventana.
         */
        get: operations["weekly_report_api_stats_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/matchups/{user_champion}/{enemy_champion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matchup Stats
         * @description Estadísticas históricas del cruce de dos campeones.
         *
         *     Filtra por campeón del usuario contra el rival de línea. Con cero partidas devuelve
         *     todo a 0 (no 404), porque la vista Matchups sigue funcionando con notas aunque no
         *     haya historial del cruce.
         */
        get: operations["matchup_stats_api_stats_matchups__user_champion___enemy_champion__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/constitution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constitution Status */
        get: operations["constitution_status_api_stats_constitution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matchup-notes/{user_champion}/{enemy_champion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Notes
         * @description Notas del cruce. Si nunca se guardó nada, devuelve notas vacías (no 404).
         */
        get: operations["get_notes_api_matchup_notes__user_champion___enemy_champion__get"];
        /**
         * Put Notes
         * @description Guarda/reemplaza las notas del cruce (PUT semantics).
         */
        put: operations["put_notes_api_matchup_notes__user_champion___enemy_champion__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scout/nemesis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nemesis */
        get: operations["nemesis_api_scout_nemesis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scout/matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matchups
         * @description Busca por campeón propio, enemigo o ambos.
         *
         *     Ambos filtros usan `ILIKE`: en Streamlit la búsqueda con los dos campos era case-sensitive y
         *     la de sólo-enemigo no, así que "jax" funcionaba en un caso y no en el otro. Además, buscar
         *     sólo por campeón propio aquí sí devuelve resultados (antes el input no hacía nada).
         */
        get: operations["matchups_api_scout_matchups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Encola la sincronización y responde al instante (202).
         *
         *     La validación (Riot ID, colas) sigue siendo síncrona: los errores de petición se reportan
         *     aquí, no en el polling. Los fallos de Riot/DB viajan después por `/status`.
         */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description Estado del sync para el polling del frontend (idle/processing/success/error).
         */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Config completa: canónicos del sistema + configuración persistida del usuario.
         *
         *     En Streamlit, `IMPACT_RATINGS` estaba hardcodeado en dos formularios distintos con riesgo
         *     de divergencia. Ahora vive en un solo sitio y se sirve desde la API.
         */
        get: operations["get_config_api_config_get"];
        /**
         * Update Config
         * @description Reemplaza champion pool y OKRs (PUT semantics).
         *
         *     El pool se limpia en el servidor: quita blancos y duplicados, respeta el máximo de 3
         *     (regla de La Constitución).
         */
        put: operations["update_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datadragon/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Datadragon Version
         * @description Parche actual de Data Dragon. El frontend lo usa para URLs de iconos.
         *
         *     Resuelve dinámicamente el hardcodeo de `current_patch = "14.24.1"` (app.py:530).
         *     Caché de 1h en el backend.
         */
        get: operations["get_datadragon_version_api_datadragon_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constitution/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constitution Status */
        get: operations["constitution_status_api_constitution_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/champions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Champions
         * @description Campeones del parche vigente. Clave = id de Data Dragon ('LeeSin'); `name` es el nombre
         *     visible que la DB guarda en matches.champion/participants.champion_name.
         */
        get: operations["champions_api_metadata_champions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Items
         * @description Objetos del parche vigente. Clave = id numérico de Riot ('3078').
         */
        get: operations["items_api_metadata_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spells
         * @description Hechizos de invocador. Clave = id numérico de partida ('4' = Flash).
         */
        get: operations["spells_api_metadata_spells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChampionMeta */
        ChampionMeta: {
            /**
             * Id
             * @description Id de Data Dragon ('LeeSin'), clave del dict
             */
            id: string;
            /**
             * Name
             * @description Nombre visible ('Lee Sin') — así se guarda en matches.champion
             */
            name: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Image
             * @description URL absoluta del cuadrado en Data Dragon
             */
            image: string;
        };
        /**
         * ChampionStats
         * @description Incluye `winrate` y `kda_ratio`, que la query original nunca devolvía pese a que la
         *     Tab 3 las pedía -> KeyError permanente. Ahora se calculan en SQL.
         */
        ChampionStats: {
            /** Champion */
            champion: string;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Kda Ratio */
            kda_ratio: number;
            /** Avg Cs Min */
            avg_cs_min: number;
            /**
             * Avg Dpm
             * @default 0
             */
            avg_dpm: number;
        };
        /** ChampionsIndex */
        ChampionsIndex: {
            /** Patch */
            patch: string;
            /** Champions */
            champions: {
                [key: string]: components["schemas"]["ChampionMeta"];
            };
        };
        /**
         * ConstitutionStatus
         * @description La regla anti-tilt, movida del sidebar de Streamlit al backend.
         *
         *     Incluye la comprobación de champion pool contra la configuración **persistida**, de modo que
         *     la alerta de "has jugado algo fuera de tus mains" ya no depende de un `text_area` volátil.
         */
        ConstitutionStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "STOP" | "ON_FIRE" | "NEUTRAL" | "NO_DATA";
            /** Message */
            message: string;
            /** Loss Streak */
            loss_streak: number;
            /**
             * Last Results
             * @description Más reciente primero; True = victoria
             */
            last_results: boolean[];
            /**
             * Last Champion
             * @description Campeón de la última partida
             */
            last_champion?: string | null;
            /**
             * Off Pool
             * @description La última partida fue fuera del champion pool
             * @default false
             */
            off_pool: boolean;
            /**
             * Champion Pool
             * @description Pool declarado, para contexto
             */
            champion_pool?: string[];
        };
        /** EndpointMetric */
        EndpointMetric: {
            /** Method */
            method: string;
            /**
             * Path
             * @description Plantilla de ruta ('/api/matches/{game_id}'), no el path literal
             */
            path: string;
            /** Count */
            count: number;
            /**
             * Errors
             * @description Peticiones terminadas en 5xx o excepción
             */
            errors: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** Max Ms */
            max_ms: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /** Riot Key Present */
            riot_key_present: boolean;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** HeatmapCell */
        HeatmapCell: {
            /**
             * Day Of Week
             * @description 0 = Domingo, 1 = Lunes ... 6 = Sábado
             */
            day_of_week: number;
            /**
             * Time Block
             * @description Madrugada | Mañana | Tarde | Noche
             */
            time_block: string;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
        };
        /** ItemMeta */
        ItemMeta: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @description Descripción sin etiquetas HTML
             * @default
             */
            description: string;
            /** Image */
            image: string;
        };
        /** ItemsIndex */
        ItemsIndex: {
            /** Patch */
            patch: string;
            /** Items */
            items: {
                [key: string]: components["schemas"]["ItemMeta"];
            };
        };
        /**
         * LpCapture
         * @description LP de Solo/Duo capturado automáticamente al cerrar el sync (League-V4).
         *
         *     `delta_assigned` es el LP neto escrito como `lp_change` en la partida más reciente sin
         *     review manual; None cuando no había snapshot previo (línea base), delta 0, o ninguna
         *     partida candidata. Nunca sobrescribe una review del usuario.
         */
        LpCapture: {
            /** Lp */
            lp: number;
            /** Tier */
            tier?: string | null;
            /** Division */
            division?: string | null;
            /** Delta Assigned */
            delta_assigned?: number | null;
        };
        /**
         * Match
         * @description Una partida. Los campos objetivos vienen de Riot; los subjetivos los rellena el usuario.
         */
        Match: {
            /** Game Id */
            game_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Champion */
            champion: string;
            /** Role */
            role: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Cs Total */
            cs_total: number;
            /** Cs Min */
            cs_min: number;
            /** Control Wards */
            control_wards: number;
            /** Win */
            win: boolean;
            /** Enemy Champion */
            enemy_champion?: string | null;
            /** Game Duration Minutes */
            game_duration_minutes?: number | null;
            /** Queue Id */
            queue_id?: number | null;
            /** Participants */
            participants?: components["schemas"]["Participant"][] | null;
            /** Lp Change */
            lp_change?: number | null;
            /** Tilt Level */
            tilt_level?: number | null;
            /** Impact Rating */
            impact_rating?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Vod Review
             * @default false
             */
            vod_review: boolean;
        };
        /**
         * MatchUpdate
         * @description Actualización parcial de los campos subjetivos.
         *
         *     Ojo: en el monolito, `update_match_details` se saltaba los `None`, así que era imposible
         *     devolver un campo a NULL. Aquí se distingue "no enviado" (ausente del JSON) de "enviado como
         *     null" usando `model_fields_set`, así que sí se puede borrar un valor mal introducido.
         */
        MatchUpdate: {
            /** Lp Change */
            lp_change?: number | null;
            /** Tilt Level */
            tilt_level?: number | null;
            /** Impact Rating */
            impact_rating?: string | null;
            /** Notes */
            notes?: string | null;
            /** Vod Review */
            vod_review?: boolean | null;
        };
        /**
         * MatchupNotes
         * @description Notas persistidas para un emparejamiento concreto.
         */
        MatchupNotes: {
            /** User Champion */
            user_champion: string;
            /** Enemy Champion */
            enemy_champion: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * MatchupNotesUpdate
         * @description Payload del PUT: reemplazo completo de las notas del cruce.
         */
        MatchupNotesUpdate: {
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * MatchupStats
         * @description Estadísticas históricas del cruce de dos campeones (Tú contra enemigo).
         */
        MatchupStats: {
            /** User Champion */
            user_champion: string;
            /** Enemy Champion */
            enemy_champion: string;
            /**
             * Games Played
             * @default 0
             */
            games_played: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Winrate
             * @default 0
             */
            winrate: number;
            /**
             * Avg Kills
             * @default 0
             */
            avg_kills: number;
            /**
             * Avg Deaths
             * @default 0
             */
            avg_deaths: number;
            /**
             * Avg Assists
             * @default 0
             */
            avg_assists: number;
            /**
             * Kda Ratio
             * @default 0
             */
            kda_ratio: number;
        };
        /** MetricsSnapshot */
        MetricsSnapshot: {
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Endpoints */
            endpoints: components["schemas"]["EndpointMetric"][];
        };
        /** Nemesis */
        Nemesis: {
            /** Enemy Champion */
            enemy_champion: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Cs Min */
            avg_cs_min: number;
        };
        /**
         * Participant
         * @description Un jugador dentro de una partida (10 por match).
         *
         *     `player_name` sustituye al viejo `summoner_name` (que Riot ya no rellena en Match-V5): ahora
         *     se guarda el Riot ID completo "GameName#TAG". Los campos con default toleran filas antiguas
         *     del JSONB sincronizadas antes del nuevo esquema, para que /api/matches no reviente; tras un
         *     TRUNCATE + resync todos los participantes salen completos.
         */
        Participant: {
            /** Champion Name */
            champion_name: string;
            /**
             * Puuid
             * @default
             */
            puuid: string;
            /**
             * Player Name
             * @description Riot ID completo 'GameName#TAG'
             * @default
             */
            player_name: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Cs */
            cs: number;
            /**
             * Items
             * @description 7 IDs de items: item0-item5 + trinket en item6 (0 = slot vacío)
             */
            items?: number[];
            /**
             * Summoner Spells
             * @description 2 IDs de hechizos
             */
            summoner_spells?: number[];
            /** Team Id */
            team_id: number;
            /** Team Position */
            team_position: string;
            /** Win */
            win: boolean;
            /**
             * Total Damage
             * @description totalDamageDealtToChampions de Riot
             * @default 0
             */
            total_damage: number;
            /**
             * Total Damage Taken
             * @default 0
             */
            total_damage_taken: number;
            /**
             * Gold Earned
             * @default 0
             */
            gold_earned: number;
            /**
             * Vision Score
             * @default 0
             */
            vision_score: number;
            /**
             * Kill Participation
             * @default 0
             */
            kill_participation: number;
            /**
             * Rating
             * @description Rating universal 0-100
             * @default 0
             */
            rating: number;
            /**
             * Rating Version
             * @description Versión de la fórmula que generó `rating` (trazabilidad)
             * @default 1
             */
            rating_version: number;
        };
        /** SpellMeta */
        SpellMeta: {
            /**
             * Id
             * @description Id numérico del hechizo en el API de partida (4 = Flash)
             */
            id: number;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Image */
            image: string;
        };
        /** SpellsIndex */
        SpellsIndex: {
            /** Patch */
            patch: string;
            /** Spells */
            spells: {
                [key: string]: components["schemas"]["SpellMeta"];
            };
        };
        /** StatsSummary */
        StatsSummary: {
            /** Total Games */
            total_games: number;
            /** Total Wins */
            total_wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Kda Ratio */
            kda_ratio: number;
            /** Avg Cs Min */
            avg_cs_min: number;
        };
        /**
         * SyncAccepted
         * @description Respuesta inmediata del POST /api/sync: el trabajo pesado corre en BackgroundTasks.
         */
        SyncAccepted: {
            /**
             * Status
             * @constant
             */
            status: "processing";
            /** Message */
            message: string;
        };
        /** SyncError */
        SyncError: {
            /** Game Id */
            game_id: string;
            /** Reason */
            reason: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * SyncResult
         * @description El sync ya no miente. El monolito decía "✨ Todo actualizado" incluso cuando un 429 había
         *     descartado partidas en silencio; ahora los fallos viajan en la respuesta.
         */
        SyncResult: {
            /** Fetched */
            fetched: number;
            /** Inserted */
            inserted: number;
            /** Skipped */
            skipped: number;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["SyncError"][];
            lp_captured?: components["schemas"]["LpCapture"] | null;
        };
        /**
         * SyncStatus
         * @description Estado del sync en curso (o del último terminado), para el polling del frontend.
         */
        SyncStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "processing" | "success" | "error";
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            result?: components["schemas"]["SyncResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * TrendPoint
         * @description Un punto de la serie temporal de KPIs de mejora (últimas N partidas válidas).
         *
         *     Orden cronológico ascendente (partida más antigua primero) para que las gráficas de
         *     línea recorran el tiempo de izquierda a derecha. `timestamp` es la hora de juego en UTC.
         */
        TrendPoint: {
            /** Game Id */
            game_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Cs Min */
            cs_min: number;
            /** Dpm */
            dpm: number;
            /** Kda */
            kda: number;
        };
        /**
         * UserSettings
         * @description Config completa del frontend: valores canónicos + configuración persistida del usuario.
         *
         *     GET /api/config devuelve todo junto para que el frontend no necesite múltiples llamadas.
         *     Los campos canónicos (impact_ratings, regions, etc.) son de solo lectura; los campos
         *     editables (champion_pool, target_cs_min, max_deaths) se actualizan con PUT.
         */
        UserSettings: {
            /** Champion Pool */
            champion_pool: string[];
            /** Target Cs Min */
            target_cs_min: number;
            /** Max Deaths */
            max_deaths: number;
            /** Updated At */
            updated_at?: string | null;
            /** Impact Ratings */
            impact_ratings?: string[];
            /** Regions */
            regions?: string[];
            /**
             * Champion Pool Max
             * @default 3
             */
            champion_pool_max: number;
            /**
             * Display Timezone
             * @default Europe/Madrid
             */
            display_timezone: string;
            /**
             * Riot Id
             * @default
             */
            riot_id: string;
            /**
             * Riot Region
             * @default EUW1
             */
            riot_region: string;
        };
        /**
         * UserSettingsUpdate
         * @description Reemplazo completo de la configuración (semántica de PUT).
         */
        UserSettingsUpdate: {
            /**
             * Champion Pool
             * @description Máximo 3 campeones (regla de La Constitución)
             */
            champion_pool: string[];
            /**
             * Target Cs Min
             * @description Meta de CS por minuto
             */
            target_cs_min: number;
            /**
             * Max Deaths
             * @description Tope de muertes por partida
             */
            max_deaths: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeeklyBestMatch
         * @description La mejor partida de la semana, según el rating 0-100 del usuario.
         */
        WeeklyBestMatch: {
            /** Game Id */
            game_id: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Champion */
            champion: string;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Kda */
            kda: number;
            /** Rating */
            rating: number;
        };
        /**
         * WeeklyReport
         * @description Resumen de los últimos 7 días (ventana según fecha UTC) para el Reporte Semanal.
         */
        WeeklyReport: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Total Games */
            total_games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /**
             * Winrate
             * @default 0
             */
            winrate: number;
            /**
             * Avg Kda
             * @default 0
             */
            avg_kda: number;
            most_played?: components["schemas"]["WeeklyTopChampion"] | null;
            best_match?: components["schemas"]["WeeklyBestMatch"] | null;
        };
        /**
         * WeeklyTopChampion
         * @description Campeón más jugado de la semana (nombre visible; el avatar lo resuelve el frontend vía Data Dragon).
         */
        WeeklyTopChampion: {
            /** Champion */
            champion: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_matches_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filtro: 'ranked' o 'normal' */
                queue?: string | null;
            };
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_matches__game_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_api_matches__game_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_stats_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    champions_api_stats_champions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_api_stats_heatmap_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapCell"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lp_trend_api_stats_lp_trend_get: {
        parameters: {
            query?: {
                limit?: number;
                queue?: number | null;
            };
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kpi_trends_api_stats_trends_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_report_api_stats_weekly_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matchup_stats_api_stats_matchups__user_champion___enemy_champion__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path: {
                user_champion: string;
                enemy_champion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constitution_status_api_stats_constitution_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstitutionStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notes_api_matchup_notes__user_champion___enemy_champion__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path: {
                user_champion: string;
                enemy_champion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupNotes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_notes_api_matchup_notes__user_champion___enemy_champion__put: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path: {
                user_champion: string;
                enemy_champion: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchupNotesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupNotes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nemesis_api_scout_nemesis_get: {
        parameters: {
            query?: {
                min_games?: number;
                limit?: number;
            };
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Nemesis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matchups_api_scout_matchups_get: {
        parameters: {
            query?: {
                /** @description Campeón propio (subcadena, case-insensitive) */
                champion?: string | null;
                /** @description Campeón enemigo (subcadena, case-insensitive) */
                enemy?: string | null;
            };
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Match"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: {
                /** @description Por defecto, el RIOT_ID del .env */
                riot_id?: string | null;
                limit?: number;
                /** @description IDs de cola separados por coma (420=Solo/Duo, 400=Normal Draft). Default: ambos. */
                queues?: string;
            };
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_api_config_put: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_datadragon_version_api_datadragon_version_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constitution_status_api_constitution_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    champions_api_metadata_champions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionsIndex"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    items_api_metadata_items_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemsIndex"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spells_api_metadata_spells_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpellsIndex"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
